# Generated by Django 3.1.2 on 2021-01-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memetest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='username',
        ),
        migrations.DeleteModel(
            name='MemeUser',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='userToken',
        ),
    ]
