# Generated by Django 3.1.2 on 2021-01-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memetest', '0002_auto_20210106_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUser',
        ),
    ]
